spring.application.name=student-backend

# Primary DB - tat de test backup
app.primary.enabled=false
spring.datasource.url=jdbc:postgresql://viaduct.proxy.rlwy.net:53388/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=UroOHCbEVypYZtJsLuhApYbpXRHgBeen
spring.datasource.driver-class-name=org.postgresql.Driver

# Secondary DB (Neon)
app.secondary.enabled=true
secondary.datasource.url=jdbc:postgresql://ep-lively-mode-ao1u72zd-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
secondary.datasource.username=neondb_owner
secondary.datasource.password=npg_jJTmrv56Qyid
secondary.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

# Application Configuration
spring.jackson.time-zone=UTC
spring.jackson.serialization.indent_output=true
server.port=${PORT:8080}

# Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890
jwt.expiration=86400000
